// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type EnterpriseDomain struct {
	ID     int64  `json:"id"`
	Domain string `json:"domain"`
}

type Runner struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Mode          string         `json:"mode"`
	Url           string         `json:"url"`
	Token         sql.NullString `json:"token"`
	Dir           sql.NullString `json:"dir"`
	Pat           sql.NullString `json:"pat"`
	ScaleSetName  sql.NullString `json:"scale_set_name"`
	MaxRunners    sql.NullInt64  `json:"max_runners"`
	Labels        sql.NullString `json:"labels"`
	RunnerGroup   sql.NullString `json:"runner_group"`
	JobsCompleted sql.NullInt64  `json:"jobs_completed"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
