// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Runner struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Mode          string    `json:"mode"`
	URL           string    `json:"url"`
	Dir           string    `json:"dir"`
	PAT           string    `json:"pat"`
	MaxRunners    int64     `json:"max_runners"`
	Labels        string    `json:"labels"`
	RunnerGroup   string    `json:"runner_group"`
	JobsCompleted int64     `json:"jobs_completed"`
	CreatedAt     time.Time `json:"created_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
