// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type EnterpriseDomain struct {
	ID     int64  `json:"id"`
	Domain string `json:"domain"`
}

type Runner struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Mode          string    `json:"mode"`
	Url           string    `json:"url"`
	Token         string    `json:"token"`
	Dir           string    `json:"dir"`
	Pat           string    `json:"pat"`
	ScaleSetName  string    `json:"scale_set_name"`
	MaxRunners    int64     `json:"max_runners"`
	Labels        string    `json:"labels"`
	RunnerGroup   string    `json:"runner_group"`
	JobsCompleted int64     `json:"jobs_completed"`
	CreatedAt     time.Time `json:"created_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
