// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runners.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRunner = `-- name: CreateRunner :one
INSERT INTO runners (
    name, mode, url, dir, pat, max_runners, labels, runner_group
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, name, mode, url, dir, pat, max_runners, labels, runner_group, jobs_completed, created_at
`

type CreateRunnerParams struct {
	Name        string `json:"name"`
	Mode        string `json:"mode"`
	URL         string `json:"url"`
	Dir         string `json:"dir"`
	PAT         string `json:"pat"`
	MaxRunners  int64  `json:"max_runners"`
	Labels      string `json:"labels"`
	RunnerGroup string `json:"runner_group"`
}

func (q *Queries) CreateRunner(ctx context.Context, arg CreateRunnerParams) (Runner, error) {
	row := q.db.QueryRowContext(ctx, createRunner,
		arg.Name,
		arg.Mode,
		arg.URL,
		arg.Dir,
		arg.PAT,
		arg.MaxRunners,
		arg.Labels,
		arg.RunnerGroup,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.URL,
		&i.Dir,
		&i.PAT,
		&i.MaxRunners,
		&i.Labels,
		&i.RunnerGroup,
		&i.JobsCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRunner = `-- name: DeleteRunner :exec
DELETE FROM runners WHERE id = ?
`

func (q *Queries) DeleteRunner(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunner, id)
	return err
}

const deleteRunnerByName = `-- name: DeleteRunnerByName :exec
DELETE FROM runners WHERE name = ?
`

func (q *Queries) DeleteRunnerByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRunnerByName, name)
	return err
}

const getRunner = `-- name: GetRunner :one
SELECT id, name, mode, url, dir, pat, max_runners, labels, runner_group, jobs_completed, created_at FROM runners WHERE id = ? LIMIT 1
`

func (q *Queries) GetRunner(ctx context.Context, id int64) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.URL,
		&i.Dir,
		&i.PAT,
		&i.MaxRunners,
		&i.Labels,
		&i.RunnerGroup,
		&i.JobsCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const getRunnerByName = `-- name: GetRunnerByName :one
SELECT id, name, mode, url, dir, pat, max_runners, labels, runner_group, jobs_completed, created_at FROM runners WHERE name = ? LIMIT 1
`

func (q *Queries) GetRunnerByName(ctx context.Context, name string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunnerByName, name)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.URL,
		&i.Dir,
		&i.PAT,
		&i.MaxRunners,
		&i.Labels,
		&i.RunnerGroup,
		&i.JobsCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const getRunnerByURLMode = `-- name: GetRunnerByURLMode :one
SELECT id, name, mode, url, dir, pat, max_runners, labels, runner_group, jobs_completed, created_at FROM runners WHERE url = ? AND mode = ? LIMIT 1
`

type GetRunnerByURLModeParams struct {
	URL  string `json:"url"`
	Mode string `json:"mode"`
}

func (q *Queries) GetRunnerByURLMode(ctx context.Context, arg GetRunnerByURLModeParams) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunnerByURLMode, arg.URL, arg.Mode)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.URL,
		&i.Dir,
		&i.PAT,
		&i.MaxRunners,
		&i.Labels,
		&i.RunnerGroup,
		&i.JobsCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const incrementJobsCompleted = `-- name: IncrementJobsCompleted :exec
UPDATE runners SET jobs_completed = jobs_completed + 1 WHERE name = ?
`

func (q *Queries) IncrementJobsCompleted(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, incrementJobsCompleted, name)
	return err
}

const listRunners = `-- name: ListRunners :many
SELECT id, name, mode, url, dir, pat, max_runners, labels, runner_group, jobs_completed, created_at FROM runners ORDER BY name ASC
`

func (q *Queries) ListRunners(ctx context.Context) ([]Runner, error) {
	rows, err := q.db.QueryContext(ctx, listRunners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Runner
	for rows.Next() {
		var i Runner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.URL,
			&i.Dir,
			&i.PAT,
			&i.MaxRunners,
			&i.Labels,
			&i.RunnerGroup,
			&i.JobsCompleted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunner = `-- name: UpdateRunner :one
UPDATE runners
SET 
    pat = COALESCE(?1, pat),
    max_runners = COALESCE(?2, max_runners),
    labels = COALESCE(?3, labels),
    runner_group = COALESCE(?4, runner_group)
WHERE id = ?5
RETURNING id, name, mode, url, dir, pat, max_runners, labels, runner_group, jobs_completed, created_at
`

type UpdateRunnerParams struct {
	PAT         sql.NullString `json:"pat"`
	MaxRunners  sql.NullInt64  `json:"max_runners"`
	Labels      sql.NullString `json:"labels"`
	RunnerGroup sql.NullString `json:"runner_group"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateRunner(ctx context.Context, arg UpdateRunnerParams) (Runner, error) {
	row := q.db.QueryRowContext(ctx, updateRunner,
		arg.PAT,
		arg.MaxRunners,
		arg.Labels,
		arg.RunnerGroup,
		arg.ID,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.URL,
		&i.Dir,
		&i.PAT,
		&i.MaxRunners,
		&i.Labels,
		&i.RunnerGroup,
		&i.JobsCompleted,
		&i.CreatedAt,
	)
	return i, err
}
